FROM centos:6
ARG MIRROR=1
WORKDIR /data

COPY ./Docker/ /data/docker/

RUN export MIRROR="$MIRROR" && \
    bash ./docker/modify_yum_source.sh && \
    yum update -y && \
    yum install -y wget autoconf automake gcc make rpm-build rpmdevtools \
        util-linux-ng perl perl-IPC-Cmd perl-Time-Piece perl-ExtUtils-Embed \
        openssl-devel libxml2-devel libxslt-devel gd-devel GeoIP-devel pcre-devel \
        zlib-devel && \
    useradd -m -u 1000 builder && \
    mkdir -p /data/output && chown builder:builder /data/output && \
    yum clean all

USER builder
RUN rpmdev-setuptree
CMD ["/data/rpmbuild.sh"]