FROM centos:5 AS builder
WORKDIR /data

COPY ./Docker/ /data/docker/
COPY ./downloads/perl-*.tar.gz /data/

RUN bash ./docker/modify_vault_source.sh && \
    yum install -y gcc44 make

RUN mkdir -p perl && tar xfz perl-*.tar.gz --strip-components=1 -C perl && pushd perl && \
    ./Configure -des -Dusethreads -Uuseshrplib -Uoptimize=-g -Dcc=gcc44 -Dprefix=/usr/local/perl && \
    make $(rpm --eval %{?_smp_mflags}) && make install_strip
RUN rm -rf perl-*.tar.gz perl


FROM centos:5
ENV PATH=/usr/local/perl/bin:$PATH
WORKDIR /data

COPY --from=builder /usr/local/perl /usr/local/perl
COPY ./Docker/ /data/docker/

RUN bash ./docker/modify_vault_source.sh && \
    yum update -y && \
    yum install -y wget autoconf automake gcc44 make rpm-build rpmdevtools \
        util-linux-ng pcre-devel zlib-devel && \
    useradd -m -u 1000 builder && \
    mkdir -p /data/output && chown builder:builder /data/output

RUN cat /etc/yum.repos.d/CentOS-Base.repo | sed 's|]$|-i386]|;s|\$basearch|i386|g' > /etc/yum.repos.d/CentOS-Base-i386.repo && \
    yum install -y glibc-devel.i386 libgcc.i386 zlib-devel.i386 pcre-devel.i386 && \
    yum clean all

USER builder
RUN echo -e "%dist .el5\n%centos 5\n" | tee -a ~/.rpmmacros
RUN rpmdev-setuptree
ENV CC=gcc44
CMD ["/data/rpmbuild.sh"]